name: Build LaTeX document
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "*"
    tags:
      - "*"


permissions:
  contents: write


jobs:
  build_latex:
    runs-on: ubuntu-latest
    if: ${{!startsWith(github.event.head_commit.message, 'skip-build') }}
    
    steps:
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Download Fonts
        uses: robinraju/release-downloader@v1.8
        with:
          tag: "Latex-lite"
          # Choose what fonts you need from https://github.com/MohammadRaziei/fonts/releases
          repository: "mohammadraziei/fonts"
          fileName: "fonts.zip"
          out-file-path: "fonts"
          extract: true

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        continue-on-error: true
        with:
          root_file: |
            main.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          extra_fonts: ./fonts/*.ttf
          # args: -synctex=1 -interaction=nonstopmode -pdfxe
          post_compile: echo ">> DONE <<" && cat main.log

      # - name: Preview files
        # run: tree --du -shaC .
        
      - name: Upload LOG files
        uses: actions/upload-artifact@v3
        with:
          name: LOG
          path: |
            main.xdv
            main.log

      - name: Rename output
        run: mv main.pdf ${{ github.actor }}-${{ steps.branch-names.outputs.base_ref_branch }}.pdf
        

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: ${{ github.actor }}-${{ steps.branch-names.outputs.base_ref_branch }}.pdf
          if-no-files-found: error

  preview:
    name: Preview
    needs: [ build_latex ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with: # download all PDF files
          name: PDF
      - name: Preview
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: "preview"
          files: |
            *.pdf


  release:
    name: Upload Release Asset
    needs: [ build_latex ]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3
        with: # download all PDF files
          name: PDF

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.pdf
